### PR TITLE
Use mysql user and password from args.

### PR DESCRIPTION
**Pull request by kovacsbalu**
Needed when "copy_data_from" database has username and password.

### CODE REVIEW

**Comment by tk0miya** [comment]
As you know, `Mysqld.dsn()` can take username and password as argument:
```
with testing.mysqld.Mysqld() as mysqld:
    db = _mysql.connect(**mysqld.dsn(user='user', passwd='passw0rd')) 
```

So this change is not needed, I think. What do you think?

**Comment by kovacsbalu** [comment]
I have my own database with user and password and this changes needed for "copy_data_from" argument. Without this fix I got:
`pymysql.err.OperationalError: (1045, u"Access denied for user 'root'@'localhost' (using password: NO)")`

**Comment by kovacsbalu** [comment]
See 439b57a

**Comment by tk0miya** [comment]
Sorry for late response.
I understand what you did. Merged just now.
Thank you for contribution!

**Comment by kovacsbalu** [comment]
No problem. Thanks for the merge! :)

**Pull request merged**
